import { useState, type FormEvent } from 'react';
import { Bell, Check, ChevronRight, Info, LogOut, Moon, RotateCcw, Save, ShieldCheck, SlidersHorizontal, Sun, Target, UserRound } from 'lucide-react';
import { Modal } from '../components/UI';
import { ContactFields, PreferenceChoices } from '../components/Onboarding';
import { useApp } from '../store';
import { LEVELS, LOCATIONS, POSITIONS, type Profile } from '../types';

export default function Settings({ onLogin }: { onLogin: () => void }) {
  const { state, updateProfile, setTheme, resetDemo, signOut } = useApp();
  const [profile, setProfile] = useState<Profile>(structuredClone(state.profile));
  const [tab, setTab] = useState('profile');
  const [resetOpen, setResetOpen] = useState(false);
  const [error, setError] = useState('');
  function submit(event: FormEvent) {
    event.preventDefault();
    if (!profile.positions.length || !profile.locations.length || !profile.levels.length) { setError('Select at least one position, location, and job type.'); return; }
    if (!profile.fullName.trim() || !profile.email.trim()) { setError('Your name and email are required in Profile.'); return; }
    setError(''); updateProfile(profile);
  }
  return <div className="settings-page"><header className="page-heading"><div><p className="eyebrow">MAKE YOURSELF AT HOME</p><h1>Your space. Your preferences.</h1><p className="muted">A job search that fits your life, not the other way around.</p></div></header><div className="settings-layout"><aside className="settings-nav panel">{[{ id: 'profile', label: 'Your profile', icon: UserRound }, { id: 'preferences', label: 'Feed preferences', icon: SlidersHorizontal }, { id: 'appearance', label: 'Appearance', icon: Moon }, { id: 'account', label: 'Account & privacy', icon: ShieldCheck }].map(item => <button className={tab === item.id ? 'active' : ''} key={item.id} onClick={() => setTab(item.id)}><item.icon size={18} />{item.label}<ChevronRight size={15} /></button>)}</aside><div className="settings-content">
    <form onSubmit={submit}>
      {tab === 'profile' && <section className="panel settings-panel"><div className="settings-section-title"><span className="settings-icon"><UserRound size={22} /></span><div><h2>A little about you</h2><p className="muted">Your introduction to the next great opportunity.</p></div></div><div className="settings-avatar-row"><span className="avatar avatar-large">{profile.fullName.split(' ').map(part => part[0]).slice(0, 2).join('')}</span><div><b>{profile.fullName}</b><span>Future looks good on you.</span></div></div><ContactFields value={profile} onChange={(key, value) => setProfile(current => ({ ...current, [key]: value }))} /><p className="settings-hint"><Info size={14} />Contact changes also update your master resume. Custom resumes stay unchanged.</p></section>}
      {tab === 'preferences' && <section className="panel settings-panel"><div className="settings-section-title"><span className="settings-icon"><SlidersHorizontal size={22} /></span><div><h2>More of your kind of thing</h2><p className="muted">We’ll prioritize these opportunities in your recommended feed.</p></div></div><PreferenceChoices label="Interested positions" options={POSITIONS} selected={profile.positions} onChange={positions => setProfile(current => ({ ...current, positions }))} /><PreferenceChoices label="Preferred Canadian locations" options={LOCATIONS} selected={profile.locations} onChange={locations => setProfile(current => ({ ...current, locations }))} /><PreferenceChoices label="Job level & employment type" options={LEVELS} selected={profile.levels} onChange={levels => setProfile(current => ({ ...current, levels }))} /><div className="weekly-settings"><div><h3><Target size={17} />Your weekly application goal</h3><p className="muted">Keep it realistic. Every step counts.</p></div><label className="field"><span className="sr-only">Weekly application goal</span><input className="input" type="number" min={1} max={50} required value={profile.weeklyGoal} onChange={event => setProfile(current => ({ ...current, weeklyGoal: Number(event.target.value) }))} /></label></div></section>}
      {(tab === 'profile' || tab === 'preferences') && <div className="settings-save">{error && <p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary" type="submit"><Save size={16} />Save changes</button></div>}
    </form>
    {tab === 'appearance' && <section className="panel settings-panel"><div className="settings-section-title"><span className="settings-icon"><Moon size={22} /></span><div><h2>A different kind of bright</h2><p className="muted">Choose a look that feels right for you.</p></div></div><div className="theme-options">{(['light', 'dark'] as const).map(theme => <button key={theme} className={`theme-option ${state.theme === theme ? 'selected' : ''}`} aria-pressed={state.theme === theme} onClick={() => setTheme(theme)}><span className={`theme-preview preview-${theme}`}><i /><span><i /><i /><i /></span></span><span>{theme === 'light' ? <Sun size={17} /> : <Moon size={17} />}{theme === 'light' ? 'A little sunshine' : 'After hours'}{state.theme === theme && <Check size={17} />}</span></button>)}</div><div className="setting-toggle-row"><div><h3>Dark mode</h3><p className="muted">Easy on the eyes. Just as full of possibility.</p></div><button type="button" role="switch" aria-checked={state.theme === 'dark'} aria-label="Dark mode" className={`toggle ${state.theme === 'dark' ? 'on' : ''}`} onClick={() => setTheme(state.theme === 'dark' ? 'light' : 'dark')}><span /></button></div></section>}
    {tab === 'account' && <section className="panel settings-panel"><div className="settings-section-title"><span className="settings-icon"><ShieldCheck size={22} /></span><div><h2>Your workspace, explained</h2><p className="muted">A little transparency goes a long way.</p></div></div><div className="notice"><Info size={20} /><div><b>You’re exploring a local demo.</b><p>Profile details, resumes, and tracked jobs are stored in this browser’s local storage. There is no secure account, cloud backup, or employer submission in this frontend demo. Avoid entering sensitive personal information on a shared device.</p></div></div><div className="account-row"><div><h3>{state.session ? 'Demo session' : 'Make your next move'}</h3><p className="muted">{state.session?.email ?? 'Try the login and registration experience.'}</p></div><button className="btn btn-secondary" onClick={state.session ? signOut : onLogin}>{state.session ? <><LogOut size={16} />Sign out</> : 'Log in / Register'}</button></div><div className="account-row"><div><h3>Google & LinkedIn SSO</h3><p className="muted">Available in the login form. Requires Django OAuth configuration.</p></div><span className="badge">Integration ready</span></div><div className="account-row danger-zone"><div><h3>Start fresh</h3><p className="muted">Remove local changes and restore the example workspace.</p></div><button className="btn btn-secondary danger-text" onClick={() => setResetOpen(true)}><RotateCcw size={15} />Reset demo</button></div></section>}
    </div></div>{resetOpen && <Modal title="Start a fresh chapter?" onClose={() => setResetOpen(false)}><p className="modal-description">This removes your locally saved profile, resumes, and application changes, and restores the example data. This cannot be undone.</p><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setResetOpen(false)}>Keep my workspace</button><button className="btn btn-danger" onClick={() => { resetDemo(); setResetOpen(false); setProfile(structuredClone(state.profile)); window.location.hash = 'discover'; }}>Reset demo</button></div></Modal>}</div>;
}
