import type { AppState, Job, Resume } from '../types';

export function daysAgo(days: number) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

const jobs: Job[] = [
  { id: 'shopify', company: 'Shopify', logo: 'shopify', color: '#eaf2db', position: 'Backend Developer', department: 'Backend', location: 'Toronto, ON', level: 'Full-time', workplace: 'Remote', salary: '$95k – $130k', description: 'Make commerce better for everyone. Build the systems that power millions of businesses, alongside a team that cares about craft as much as you do.', requirements: ['Experience building APIs and scalable backend services', 'A solid foundation in data structures and relational databases', 'Curiosity, ownership, and a love for solving hard problems'], skills: ['Ruby on Rails', 'GraphQL', 'PostgreSQL', 'Redis'], postedAt: daysAgo(0), match: 98, featured: true, about: 'Shopify is a global commerce company helping entrepreneurs start, grow, and manage their businesses. Work on meaningful challenges with a remote-first team across Canada.' },
  { id: 'linear', company: 'Linear', logo: 'linear', color: '#ecebff', position: 'Fullstack Engineer', department: 'Fullstack', location: 'Remote, Canada', level: 'Full-time', workplace: 'Remote', salary: '$110k – $155k', description: 'Bring a little more delight to the way teams build software. Help us craft fast, thoughtful product experiences used by the world’s most ambitious teams.', requirements: ['Experience shipping production React and TypeScript applications', 'Strong attention to interaction design and performance', 'Comfort working across the stack with a distributed team'], skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'], postedAt: daysAgo(1), match: 95, about: 'Linear is on a mission to bring back the magic of software. Our small, distributed team builds opinionated tools for planning and building products.' },
  { id: 'notion', company: 'Notion', logo: 'notion', color: '#f2f0ec', position: 'Software Engineering Intern', department: 'Frontend', location: 'Vancouver, BC', level: 'Internship', workplace: 'Hybrid', salary: '$35 – $48 / hr', description: 'Help millions of people turn their ideas into something real. Join a small, collaborative team building the next generation of connected workspaces.', requirements: ['Currently pursuing a degree in computer science or a related field', 'Familiarity with JavaScript, React, and web fundamentals', 'A portfolio of projects you are excited to talk about'], skills: ['React', 'JavaScript', 'CSS', 'Figma'], postedAt: daysAgo(2), match: 92, about: 'Notion gives people the tools to make their own software, without having to write code. Join a team that values thoughtful design, creativity, and collaboration.' },
  { id: 'wealthsimple', company: 'Wealthsimple', logo: 'wealthsimple', color: '#f5e7d9', position: 'Platform Engineer', department: 'DevOps', location: 'Toronto, ON', level: 'Full-time', workplace: 'Hybrid', salary: '$100k – $140k', description: 'Build a more human financial future. Help our engineering teams ship with confidence through reliable infrastructure and a world-class developer experience.', requirements: ['Experience with cloud infrastructure and infrastructure as code', 'Working knowledge of Kubernetes and CI/CD pipelines', 'A collaborative approach to reliability and incident response'], skills: ['AWS', 'Kubernetes', 'Terraform', 'Python'], postedAt: daysAgo(4), match: 89, about: 'Wealthsimple is on a mission to help everyone achieve financial freedom. We build simple, sophisticated financial products for Canadians.' },
  { id: 'figma', company: 'Figma', logo: 'figma', color: '#f6e6ef', position: 'Frontend Software Engineer', department: 'Frontend', location: 'Remote, Canada', level: 'Entry-level', workplace: 'Remote', salary: '$85k – $115k', description: 'Make design accessible to everyone. Create intuitive interfaces and delightful details that help teams go from their first idea to their next big thing.', requirements: ['Strong JavaScript and CSS fundamentals', 'Experience with React and accessible UI development', 'An interest in design tools and collaborative software'], skills: ['React', 'TypeScript', 'WebGL', 'CSS'], postedAt: daysAgo(5), match: 94, about: 'Figma helps teams design and build products together. We believe great design is a collaborative effort, and we are building the tools to make it happen.' },
  { id: 'clio', company: 'Clio', logo: 'clio', color: '#e3edfa', position: 'Junior Backend Developer', department: 'Backend', location: 'Vancouver, BC', level: 'Entry-level', workplace: 'Hybrid', salary: '$75k – $100k', description: 'Use your skills to make the legal system more accessible. Build thoughtful, reliable software that gives legal professionals more time to help their clients.', requirements: ['Foundational knowledge of object-oriented programming', 'Experience with SQL databases and REST APIs', 'A growth mindset and an eagerness to learn'], skills: ['Ruby', 'Rails', 'MySQL', 'Docker'], postedAt: daysAgo(6), match: 91, about: 'Clio is transforming the legal experience for all. We are a Canadian-founded technology company building the operating system for legal professionals.' },
  { id: '1password', company: '1Password', logo: '1password', color: '#e2ecff', position: 'Security Software Developer', department: 'Security', location: 'Remote, Canada', level: 'Full-time', workplace: 'Remote', salary: '$100k – $145k', description: 'Help people stay safe online without slowing them down. Build secure, human-friendly tools trusted by millions of people and businesses around the world.', requirements: ['Experience with Go, Rust, or a similar systems language', 'An understanding of authentication and applied cryptography', 'A passion for privacy and usable security'], skills: ['Go', 'Rust', 'Security', 'Linux'], postedAt: daysAgo(7), match: 87, about: '1Password is creating a safer, simpler digital future. Our remote-first team builds security products that put people first.' },
  { id: 'ada', company: 'Ada', logo: 'ada', color: '#eee5f8', position: 'Machine Learning Developer', department: 'Data & AI', location: 'Montréal, QC', level: 'Part-time', workplace: 'Remote', salary: '$50 – $65 / hr', description: 'Make every customer interaction a little more helpful. Build practical AI systems that bring great support to people, wherever and whenever they need it.', requirements: ['Experience with Python and machine learning frameworks', 'Understanding of LLMs and evaluation techniques', 'Ability to communicate technical ideas clearly'], skills: ['Python', 'PyTorch', 'LLMs', 'SQL'], postedAt: daysAgo(9), match: 85, about: 'Ada is an AI-powered customer service platform. We help ambitious businesses deliver extraordinary customer experiences at scale.' },
];

export function createInitialState(): AppState {
  const contact = { fullName: 'Alex Morgan', email: 'alex.morgan@example.com', phone: '+1 (416) 555-0142', location: 'Toronto, ON', website: 'alexmorgan.dev', linkedin: 'linkedin.com/in/alexmorgan' };
  const master: Resume = {
    id: 'master', name: 'Master resume', jobId: null, updatedAt: daysAgo(2), contact,
    sections: {
      education: [{ id: 'edu-1', title: 'University of Toronto', subtitle: 'Bachelor of Science in Computer Science', location: 'Toronto, ON', period: '2022 – 2026', details: 'Relevant coursework: Data Structures, Algorithms, Database Systems, Software Engineering\nDean’s List · GPA: 3.8 / 4.0', visible: true }],
      experience: [{ id: 'exp-1', title: 'Software Developer Intern', subtitle: 'Acme Technologies', location: 'Toronto, ON', period: 'May 2025 – Aug 2025', details: 'Built REST APIs serving 10,000+ daily requests using Node.js and PostgreSQL.\nReduced page load times by 32% through query optimization and caching.\nCollaborated with a cross-functional team to ship three customer-facing features.', visible: true }],
      skills: [{ id: 'skill-1', title: 'Languages & frameworks', subtitle: '', location: '', period: '', details: 'TypeScript, JavaScript, Python, Java, React, Node.js, Ruby on Rails', visible: true }, { id: 'skill-2', title: 'Tools & technologies', subtitle: '', location: '', period: '', details: 'PostgreSQL, Git, Docker, AWS, GraphQL, Figma', visible: true }],
      projects: [{ id: 'project-1', title: 'Campus Connect', subtitle: 'React · Node.js · PostgreSQL', location: '', period: '2025', details: 'Designed and built a full-stack platform connecting 200+ students with campus events.\nImplemented real-time notifications and role-based authentication.', visible: true }, { id: 'project-2', title: 'Open Source Contributions', subtitle: 'TypeScript · GitHub', location: '', period: '2024 – Present', details: 'Contributed accessibility fixes and documentation improvements to community React projects.', visible: true }],
    },
  };
  const custom = structuredClone(master);
  custom.id = 'custom-wealthsimple';
  custom.name = 'Wealthsimple · Platform Engineer';
  custom.jobId = 'wealthsimple';
  custom.sections.skills[0].details = 'Python, TypeScript, AWS, Docker, Terraform, PostgreSQL';
  return {
    profile: { ...contact, positions: ['Backend', 'Fullstack', 'Frontend'], locations: ['Toronto, ON', 'Remote, Canada'], levels: ['Full-time', 'Entry-level', 'Internship'], weeklyGoal: 5 },
    jobs,
    applications: [
      { id: 'app-wealthsimple', jobId: 'wealthsimple', status: 'Interview', appliedDate: daysAgo(3), resumeId: custom.id, saved: false, notifications: [{ id: 'notification-1', title: 'You’re moving forward!', message: 'Demo notification: Wealthsimple would like to schedule an introductory interview.', date: daysAgo(1), channel: 'Email' }, { id: 'notification-2', title: 'Application recorded', message: 'Your application with a custom resume was added to your tracker.', date: daysAgo(3), channel: 'In-app' }] },
      { id: 'app-figma', jobId: 'figma', status: 'Applied', appliedDate: daysAgo(2), resumeId: 'master', saved: false, notifications: [{ id: 'notification-3', title: 'Application recorded', message: 'Your application with your master resume was added to your tracker.', date: daysAgo(2), channel: 'In-app' }] },
      { id: 'app-clio', jobId: 'clio', status: 'Saved', appliedDate: null, resumeId: null, saved: true, notifications: [] },
      { id: 'app-1password', jobId: '1password', status: 'Offer', appliedDate: daysAgo(7), resumeId: 'master', saved: true, notifications: [{ id: 'notification-4', title: 'An exciting next step', message: 'Demo notification: a new offer has been added to your application.', date: daysAgo(0), channel: 'Email' }] },
      { id: 'app-ada', jobId: 'ada', status: 'Rejection', appliedDate: daysAgo(8), resumeId: 'master', saved: false, notifications: [] },
    ],
    resumes: [master, custom], theme: 'light', onboarded: false, session: null,
  };
}
